/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Addition */

#ifndef _Included_Addition
#define _Included_Addition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Addition
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Addition_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
